spring.jackson.serialization.FAIL_ON_EMPTY_BEANS: false
server.port: 8580
autologin.enabled: true
autologin.hostName: localhost
autologin.port: 40151
autologin.username: n1
autologin.password: client123!